import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";
import { PKG_MGR_ROOT, PACKAGES_DIR, REPOS_DIR } from "./constants.js";
import { loadRegistry, saveRegistry } from "./registry.js";

// ============================================================================
// Git-enable the pool
// ============================================================================

/**
 * Initialize git in the packagemanager root and set the remote.
 * If already initialized, just update the remote.
 */
export function gitInitPool(remote: string): void {
  mkdirSync(PKG_MGR_ROOT, { recursive: true });

  const gitDir = join(PKG_MGR_ROOT, ".git");
  if (!existsSync(gitDir)) {
    execSync("git init", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
  }

  // Set or update remote
  try {
    execSync("git remote get-url origin", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    execSync(`git remote set-url origin ${remote}`, { cwd: PKG_MGR_ROOT, stdio: "pipe" });
  } catch {
    execSync(`git remote add origin ${remote}`, { cwd: PKG_MGR_ROOT, stdio: "pipe" });
  }

  // Save remote in registry
  const reg = loadRegistry();
  reg.gitRemote = remote;
  saveRegistry(reg);

  // Ensure gitignore is correct
  ensureGitignore();

  // Initial commit if needed
  try {
    execSync("git rev-parse HEAD", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
  } catch {
    execSync("git add -A", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    execSync('git commit -m "Initial package manager setup"', { cwd: PKG_MGR_ROOT, stdio: "pipe" });
  }
}

// ============================================================================
// Sync (push/pull)
// ============================================================================

export function gitSyncPool(onProgress?: (msg: string) => void): { pulled: boolean; pushed: boolean; message: string } {
  const result = { pulled: false, pushed: false, message: "" };
  const progress = onProgress || (() => {});

  if (!isGitEnabled()) {
    result.message = "Git is not enabled for the package pool. Use /packages-git-init <remote> first.";
    return result;
  }

  // Stage any changes
  progress("📦 Staging changes...");
  execSync("git add -A", { cwd: PKG_MGR_ROOT, stdio: "pipe" });

  // Commit if there are changes
  try {
    const status = execSync("git status --porcelain", { cwd: PKG_MGR_ROOT, encoding: "utf-8" }).trim();
    if (status) {
      progress("📦 Committing local changes...");
      execSync('git commit -m "Package manager sync"', { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    } else {
      progress("📦 No local changes to commit.");
    }
  } catch {}

  // Pull with rebase
  try {
    progress("📦 Pulling from remote...");
    execSync("git pull --rebase origin main 2>/dev/null || git pull --rebase origin master 2>/dev/null || true", {
      cwd: PKG_MGR_ROOT,
      stdio: "pipe",
      shell: "/bin/bash",
    });
    result.pulled = true;
  } catch (e: any) {
    result.message = `Pull failed: ${e.message}`;
    return result;
  }

  // Push
  try {
    progress("📦 Pushing to remote...");
    execSync("git push -u origin HEAD", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    result.pushed = true;
    result.message = "Synced successfully.";
  } catch (e: any) {
    result.message = `Pushed failed: ${e.message}. Pull succeeded.`;
  }

  return result;
}

// ============================================================================
// Gitignore management
// ============================================================================

/**
 * Regenerate .gitignore to ignore git/npm packages and generated repos.
 * Local packages are tracked.
 */
export function ensureGitignore(): void {
  if (!isGitEnabled()) return;

  const reg = loadRegistry();
  const lines: string[] = [
    "# Auto-generated by pi-package-manager — do not edit manually",
    "# Git/npm packages are reproducible from registry.json",
    "# Local/onboarded packages are tracked in git",
    "",
    "# Generated per-machine repo packages",
    "repos/",
    "",
  ];

  // Ignore git and npm sourced packages
  const ignoredPackages: string[] = [];
  for (const [name, entry] of Object.entries(reg.packages)) {
    if (entry.sourceType === "git" || entry.sourceType === "npm") {
      ignoredPackages.push(name);
    }
  }

  if (ignoredPackages.length > 0) {
    lines.push("# Git/npm sourced packages (install from registry.json)");
    for (const name of ignoredPackages.sort()) {
      lines.push(`packages/${name}/`);
    }
    lines.push("");
  }

  writeFileSync(join(PKG_MGR_ROOT, ".gitignore"), lines.join("\n"));
}

// ============================================================================
// Push only
// ============================================================================

/**
 * Stage, commit, and push the pool to its git remote.
 */
export function gitPushPool(): { success: boolean; message: string } {
  if (!isGitEnabled()) {
    return { success: false, message: "Git is not enabled for the package pool. Use /packages-git-init <remote> first." };
  }

  try {
    execSync("git add -A", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    const status = execSync("git status --porcelain", { cwd: PKG_MGR_ROOT, encoding: "utf-8" }).trim();
    if (status) {
      execSync('git commit -m "Package manager sync"', { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    }
    execSync("git push -u origin HEAD", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    return { success: true, message: status ? "Committed and pushed pool to remote." : "Nothing to commit — pushed to remote." };
  } catch (e: any) {
    return { success: false, message: e.message };
  }
}

// ============================================================================
// Pool update check / pull
// ============================================================================

/**
 * Check if the pool git remote has newer commits.
 */
export function checkPoolUpdate(): boolean {
  if (!isGitEnabled()) return false;
  try {
    execSync("git fetch --depth=1", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    const local = execSync("git rev-parse HEAD", { cwd: PKG_MGR_ROOT, encoding: "utf-8" }).trim();
    const remote = execSync("git rev-parse FETCH_HEAD", { cwd: PKG_MGR_ROOT, encoding: "utf-8" }).trim();
    return local !== remote;
  } catch {
    return false;
  }
}

/**
 * Pull the pool from its git remote (rebase).
 */
export function gitPullPool(): { success: boolean; message: string } {
  if (!isGitEnabled()) {
    return { success: false, message: "Git is not enabled for the pool." };
  }
  try {
    execSync("git fetch --depth=1", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    execSync("git reset --hard FETCH_HEAD", { cwd: PKG_MGR_ROOT, stdio: "pipe" });
    const commit = execSync("git rev-parse --short HEAD", { cwd: PKG_MGR_ROOT, encoding: "utf-8" }).trim();
    return { success: true, message: `Pool updated to ${commit}.` };
  } catch (e: any) {
    return { success: false, message: e.message };
  }
}

// ============================================================================
// Helpers
// ============================================================================

export function isGitEnabled(): boolean {
  return existsSync(join(PKG_MGR_ROOT, ".git"));
}

export function getGitRemote(): string | undefined {
  const reg = loadRegistry();
  return reg.gitRemote;
}
